[tox]
envlist = tests,tools,clean
skip_missing_interpreters = true
skipsdist = true

[testenv]
skip_install = true
install_command = pip install {opts} {packages}
#basepython= python3.9

[testenv:tests]
description =
    Run the full openscap unit/integration test suite with ctest

setenv =
    CC = {env:CC:gcc}
    CXX = {env:CXX:g++}
    CPUS = {env:CPUS:4}
    BUILD_TYPE = {env:BUILD_TYPE:RelWithDebInfo}
    PREFIX = {env:PREFIX:{envdir}}
    ENABLE_TESTS = {env:ENABLE_TESTS:ON}

passenv =
    CFLAGS
    CXXFLAGS
    LDFLAGS
    AR
    NM
    RANLIB
    PYTHON
    DISPLAY
    XAUTHORITY
    HOME
    USERNAME
    USER
    CI
    XDG_*
    GITHUB*
    PIP_DOWNLOAD_CACHE

deps =
    pip>=22.1
    cmake
    ninja

commands =
    cmake -G {posargs:"Unix Makefiles"} -S . -B build -DCMAKE_BUILD_TYPE={env:BUILD_TYPE} -DENABLE_TESTS={env:ENABLE_TESTS}
    cmake --build build -j{env:CPUS}
    ctest -V -j{env:CPUS} --rerun-failed --output-on-failure --test-dir build/

[testenv:tools]
skip_install = true
envdir = {toxworkdir}/tools

description =
    Build and install openscap into the {env:PREFIX} path (default: tools)

allowlist_externals =
    bash

deps =
    {[testenv:tests]deps}

setenv =
    CC = {env:CC:gcc}
    CXX = {env:CXX:g++}
    CPUS = {env:CPUS:4}
    BUILD_TYPE = {env:BUILD_TYPE:Release}
    PREFIX = {env:PREFIX:{envdir}}
    WITH_RPATH = {env:LOCAL_INSTALL_WITH_RPATH:ON}

passenv =
    {[testenv:tests]passenv}

commands =
    cmake -G {posargs:"Unix Makefiles"} -S . -B build -DCMAKE_BUILD_TYPE={env:BUILD_TYPE} -DCMAKE_INSTALL_PREFIX={env:PREFIX} -DENABLE_TESTS=OFF -DBUILD_SHARED_LIBS=OFF -DLOCAL_INSTALL_WITH_RPATH={env:WITH_RPATH}
    cmake --build build -j{env:CPUS} --target install
    bash -c 'find $PREFIX/ -maxdepth 3 -type d'

[testenv:clean]
skip_install = true
description =
    Clean the cmake build tree

allowlist_externals =
    {[testenv:tools]allowlist_externals}

deps =
    pip>=21.1

commands =
    bash -c 'rm -rf build/*'
